.\" Manpage for doggy_watcher
.\" Contact jorgedelaflor@gmail.com to correct errors or typos.
.TH man 1 "21 May 2016" "1.0" "doggy man page"
.SH NAME
\fBdoggy_watcher\fR \- doggy wrapper
.SH SYNOPSIS
\fBdoggy_watcher\fR
.SH DESCRIPTION
doggy_watcher is a wrapper for doggy application. It keeps doggy's output stored in files, and rolls them periodically.
Sending USR1 to doggy_watcher 
.SH OPTIONS
doggy_watcher does not take any options.
It is fully configured via doggy_parameters.conf
.SH SEE ALSO
doggy(1),doggy_parameters.conf(5)
.SH BUGS
No known bugs.
.SH AUTHOR
Jorge de la Flor (jorgedelaflor@gmail.com)
