.\" Manpage for doggy
.\" Contact jorgedelaflor@gmail.com to correct errors or typos.
.TH man 1 "21 May 2016" "1.0" "doggy man page"
.SH NAME
\fBdoggy\fR \- Third party dummy application with a random stop bug
.SH SYNOPSIS
\fBdoggy\fR
.SH DESCRIPTION
doggy is the third party dummy application with a random stop bug developed for this exercise in order to test the exercise pourposed application.
.SH OPTIONS
doggy does not take any options.
.SH SEE ALSO
doggy_watcher(1),doggy_parameters.conf(5)
.SH BUGS
No known bugs.
.SH AUTHOR
Jorge de la Flor (jorgedelaflor@gmail.com)
