.\" Manpage for doggy_parameters.conf
.\" Contact jorgedelaflor@gmail.com to correct errors or typos.
.TH man 5 "21 May 2016" "1.0" "doggy_parameters.conf man page"
.SH NAME
.I doggy_parameters.conf 
\- doggy_watcher configuration file
.SH SYNOPSIS
.I doggy_parameters.conf
.SH DESCRIPTION
doggy_parameters.conf is doggy watcher configuration file. It should be deployed in the same directoryof doggy_watcher. 

It accepts standard comment lines starting them with '#' character.
Empty lines are also suported.

Parameters:
.TP
\fBinstances\fR: Number of doggy instances. Must be an int. Default value: '2'
.TP
\fBpath\fR : doggy path. Can be absolute or relative. Default value: './doggy'
.TP
\fBlog_size\fR : Maximum size before log rerroll in bytes. Must be a long long. Default value: '1024'

.SH EXAMPLE
Example doggy_parameters.conf:
.RS 14 
.br
instances=5
.br 
path=./doggy
.br
size=512
.SH SEE ALSO
doggy_watcher(1),doggy(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Jorge de la Flor (jorgedelaflor@gmail.com)
